[package]
name = "compression-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
brotli = "7.0"
lz4 = "1.28"
zstd = "0.13"
snap = "1.1"  # Snappy compression (for comparison)

