<script module lang="ts">
	export const prerender = true;
</script>

<script lang="ts">
	import Reveal from '$lib/blog/Reveal.svelte';
	import Figure from '$lib/blog/Figure.svelte';
	import DiagramRouter from '$lib/blog/DiagramRouter.svelte';
	import DiagramShardMap from '$lib/blog/DiagramShardMap.svelte';
	import DiagramPipeline from '$lib/blog/DiagramPipeline.svelte';
	import DiagramLocalVsCloud from '$lib/blog/DiagramLocalVsCloud.svelte';
</script>

<svelte:head>
	<title>The Free Dictionary Engine — Kiokun</title>
	<meta
		name="description"
		content="How Kiokun hosts 435,000 dictionary files for $0 across 30 GitHub repositories, addresses any word with a single hash, and rebuilds itself in the cloud."
	/>
</svelte:head>

<article>
	<header class="masthead">
		<a class="back" href="/blog">← Kiokun Notebook</a>
		<p class="kicker">Infrastructure</p>
		<h1>The dictionary that hosts itself</h1>
		<p class="deck">
			Four hundred and thirty-five thousand files. No database, no storage bill, and a
			build that runs without me. The whole thing is a hash and a git push.
		</p>
		<p class="byline">
			<span>Kiokun Engineering</span><span class="dot">·</span><span>data architecture</span
			><span class="dot">·</span><span>12 min</span>
		</p>
	</header>

	<div class="prose">
		<Reveal as="section">
			<p class="lede">
				<span class="dropcap">K</span>iokun is a Chinese–Japanese–Korean dictionary. Look up a
				character and you get readings, senses, decompositions, example sentences — a dense
				little dossier per entry, and there are about <b>435,000</b> of them. Early on this
				lived in Cloudflare R2, an object store that bills per request and per gigabyte. It
				worked. It also meant a meter ran every time someone tapped a word.
			</p>
			<p>
				The replacement has no storage bill at all. It is a pile of public GitHub
				repositories, addressed by arithmetic, and rebuilt by the same push that ships the
				code. This is how the pieces fit.
			</p>
		</Reveal>

		<Reveal as="section">
			<h2><span class="num">I</span> One word, one path</h2>
			<p>
				There is no lookup table and no search index. Given a word, the client computes
				where its file lives. The address has two coordinates, and a single integer hash
				produces both.
			</p>
			<p>
				First, the word is classified by how many Han characters it contains — none, one,
				two, or three-plus. That picks a <em>family</em> of repositories. Within the family,
				<code>hash % N</code> chooses the specific repo, and the low byte of that very same
				hash, <code>hash &amp; 0xff</code>, chooses one of 256 subdirectories. The hash is a
				plain rolling <code>h = h·31 + c</code> — trivial on purpose, because the Rust
				generator and the TypeScript client must agree to the bit.
			</p>
		</Reveal>

		<Reveal as="div">
			<Figure
				n={1}
				bleed
				title="Addressing"
				caption="Han-count selects a family; one hash fixes both the repository and the subdirectory."
			>
				<DiagramRouter />
			</Figure>
		</Reveal>

		<Reveal as="section">
			<p>
				The payoff: resolving a word is <em>pure computation</em>. The browser builds a
				URL and fetches one deflate-compressed JSON file. No round-trip to ask "where is
				it?" — the question answers itself.
			</p>
		</Reveal>

		<Reveal as="section">
			<h2><span class="num">II</span> The 256-folder trick</h2>
			<p>
				Spreading files across thirty repositories keeps any single repo around ten to
				thirteen thousand files. That alone isn't enough. Git — and GitHub's UI, API, and
				the CDNs that mirror it — get unhappy with directories that hold tens of thousands
				of entries. A flat folder of 45,000 files is a slow folder.
			</p>
			<blockquote>
				So the second coordinate isn't decoration. It's the difference between a directory
				of forty files and a directory of forty-five thousand.
			</blockquote>
			<p>
				Hence <code>00</code> through <code>ff</code>: 256 subdirectories per repo, each
				holding a comfortable few dozen files. The commit tree for a shard drops from
				~26&nbsp;MB to single digits, and every level of the stack — git, GitHub, jsDelivr —
				stays in its happy path.
			</p>
		</Reveal>

		<Reveal as="div">
			<Figure
				n={2}
				bleed
				title="Fan-out"
				caption="30 repositories, and 256 hash-keyed subdirectories inside each one."
			>
				<DiagramShardMap />
			</Figure>
		</Reveal>

		<Reveal as="section">
			<h2><span class="num">III</span> The build runs itself</h2>
			<p>
				The dictionary is generated by Rust from upstream sources — JMdict, Kanjidic2,
				JMnedict and friends. The interesting part isn't the parsing; it's that I never run
				it. A push to <code>kiokun-data</code> that touches <code>src/**</code> or
				<code>Cargo.toml</code> triggers a GitHub Actions workflow whose matrix has one entry
				per active shard. Twenty-eight jobs start at once.
			</p>
			<p>
				Each lane compiles the generator, runs
				<code>build_dictionary --mode &lt;shard&gt; --prod</code>, then clones its target
				repo, lays down the files, and commits onto a fresh <em>orphan</em> branch that is
				force-pushed over <code>main</code>. No history is kept — each deploy is a clean
				snapshot, which is exactly why the repos stay small.
			</p>
		</Reveal>

		<Reveal as="div">
			<Figure
				n={3}
				bleed
				title="The matrix"
				caption="One push → 28 parallel lanes → 28 repositories, each replaced wholesale."
			>
				<DiagramPipeline />
			</Figure>
		</Reveal>

		<Reveal as="section">
			<h2><span class="num">IV</span> Don't upload what you can generate</h2>
			<p>
				This is the part worth internalising. Building the dictionary locally and pushing
				the result means 435,000 files — hundreds of megabytes — have to climb my home
				upload link to reach GitHub. The compute is fast; the <em>transfer</em> is the wall.
			</p>
			<p>
				Generating in CI inverts it. I push a few kilobytes of Rust. The runner builds and
				commits <em>inside GitHub's own network</em>, a few milliseconds from the
				destination repositories. The heavy bytes are born where they need to live and
				never travel over a residential connection at all.
			</p>
		</Reveal>

		<Reveal as="div">
			<Figure
				n={4}
				bleed
				title="Locality"
				caption="Move the computation to the data, not 435K files to the cloud."
			>
				<DiagramLocalVsCloud />
			</Figure>
		</Reveal>

		<Reveal as="section">
			<h2><span class="num">V</span> The bill, and the fine print</h2>
			<p>
				Hosting: <b>$0/month</b>. Static files on public GitHub repos, served through raw
				URLs and jsDelivr's global CDN, with no egress meter. The honest tradeoffs: deploys
				are eventually consistent while 28 repos settle; force-pushing orphan branches is a
				deliberate amnesia, not an accident; and raw GitHub is preferred over jsDelivr in
				production specifically to dodge cross-region cache skew.
			</p>
			<p>
				None of this is exotic. It's a hash function, a folder convention, and a CI matrix
				pointed at the obvious conclusion — that the cheapest, fastest place to assemble a
				large dataset is next to where it will be served. <span class="end-seal"
					aria-hidden="true"></span>
			</p>
		</Reveal>

		<Reveal as="footer">
			<a class="back foot" href="/blog">← More from the Kiokun Notebook</a>
		</Reveal>
	</div>
</article>

<style>
	article {
		padding: clamp(2rem, 7vw, 5.5rem) var(--gutter) 6rem;
	}
	.masthead,
	.prose {
		max-width: var(--measure);
		margin-inline: auto;
	}
	.back {
		font-family: var(--label);
		font-size: 0.78rem;
		letter-spacing: 0.06em;
		color: var(--ink-faint);
		text-decoration: none;
	}
	.back:hover {
		color: var(--shu);
	}
	.kicker {
		margin: 2rem 0 0.8rem;
		font-family: var(--label);
		font-size: 0.74rem;
		font-weight: 600;
		letter-spacing: 0.24em;
		text-transform: uppercase;
		color: var(--shu);
	}
	h1 {
		margin: 0;
		font-family: var(--display);
		font-weight: 600;
		font-size: clamp(2.4rem, 7vw, 4.4rem);
		line-height: 1.04;
		letter-spacing: -0.02em;
		color: var(--ink);
	}
	.deck {
		margin: 1.3rem 0 0;
		font-family: var(--body);
		font-size: clamp(1.15rem, 2.4vw, 1.5rem);
		line-height: 1.5;
		color: var(--ink-soft);
		max-width: 32rem;
	}
	.byline {
		display: flex;
		flex-wrap: wrap;
		gap: 0.6rem;
		margin: 2rem 0 0;
		padding-top: 1.3rem;
		border-top: 1px solid var(--rule);
		font-family: var(--label);
		font-size: 0.78rem;
		letter-spacing: 0.06em;
		color: var(--ink-faint);
	}
	.dot {
		opacity: 0.5;
	}

	.prose {
		margin-top: clamp(2.5rem, 7vw, 4.5rem);
		font-size: 1.16rem;
		line-height: 1.72;
		color: var(--ink-soft);
	}
	.prose :global(section),
	.prose :global(footer) {
		margin-block: clamp(1.6rem, 5vw, 2.6rem);
	}
	.prose p {
		margin: 1.05em 0;
	}
	.prose b {
		color: var(--ink);
		font-weight: 600;
		font-variant-numeric: tabular-nums;
	}
	.prose em {
		font-style: italic;
		color: var(--ink);
	}
	.lede {
		font-size: 1.05em;
	}
	.dropcap {
		float: left;
		font-family: var(--display);
		font-weight: 800;
		font-size: 4.4rem;
		line-height: 0.78;
		padding: 0.3rem 0.6rem 0 0;
		color: var(--shu);
	}
	h2 {
		display: flex;
		align-items: baseline;
		gap: 0.85rem;
		margin: 0 0 0.6rem;
		font-family: var(--display);
		font-weight: 600;
		font-size: clamp(1.55rem, 3.6vw, 2.15rem);
		line-height: 1.15;
		letter-spacing: -0.015em;
		color: var(--ink);
	}
	.num {
		font-size: 0.7em;
		font-weight: 500;
		color: var(--shu);
		font-variant-numeric: oldstyle-nums;
		letter-spacing: 0.05em;
	}
	code {
		font-family: var(--label);
		font-size: 0.86em;
		font-weight: 600;
		color: var(--shu);
		background: color-mix(in oklch, var(--shu-wash) 40%, transparent);
		padding: 0.06em 0.34em;
		border-radius: 3px;
		white-space: nowrap;
	}
	blockquote {
		margin: 1.8rem 0;
		padding-left: 1.4rem;
		border-left: 3px solid var(--shu);
		font-family: var(--display);
		font-size: 1.32rem;
		font-style: italic;
		line-height: 1.45;
		color: var(--ink);
	}
	.end-seal {
		display: inline-block;
		width: 0.72em;
		height: 0.72em;
		margin-left: 0.15em;
		background: var(--shu);
		border-radius: 2px;
		transform: translateY(0.02em) rotate(-4deg);
		vertical-align: baseline;
	}
	.foot {
		display: inline-block;
		margin-top: 2rem;
		padding-top: 1.4rem;
		border-top: 1px solid var(--rule);
		width: 100%;
	}
</style>
