#:schema node_modules/wrangler/config-schema.json
name = "kiokun-dictionary"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".svelte-kit/cloudflare"

# D1 Database binding for dictionary data
[[d1_databases]]
binding = "DB"
database_name = "kiokun-dictionary"
database_id = "YOUR_DATABASE_ID_HERE" # Replace with your actual database_id from `wrangler d1 create kiokun-dictionary`

