name: Deploy Dictionary to 10 GitHub Repos (jsDelivr CDN - Deflate Compressed)

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'data/**'
      - 'Cargo.toml'
      - '.github/workflows/deploy-to-github-23-shards.yml'
  workflow_dispatch:  # Manual trigger also available

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard:
          - non-han
          - han-1char-1
          - han-1char-2
          - han-2char-1
          - han-2char-2
          - han-2char-3
          - han-3plus-1
          - han-3plus-2
          - han-3plus-3
          - reserved
      fail-fast: false  # Continue even if one shard fails
      max-parallel: 10  # Deploy all 10 shards in parallel
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          lfs: false
      
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      - name: Download JMdict files
        run: |
          mkdir -p data
          cd data

          # Download JMdict examples
          curl -L -o jmdict-examples.json.tgz \
            https://github.com/scriptin/jmdict-simplified/releases/download/3.6.1%2B20251013122507/jmdict-examples-eng-3.6.1%2B20251013122507.json.tgz
          tar -xzf jmdict-examples.json.tgz
          ls -la  # Debug: see what files were extracted
          # Find and rename the extracted file (handle any filename variations)
          find . -name "jmdict-examples-eng-3.6.1*.json" -exec mv {} jmdict-examples-eng-3.6.1.json \;
          rm jmdict-examples.json.tgz

          # Download Kanjidic2
          curl -L -o kanjidic2.json.tgz \
            https://github.com/scriptin/jmdict-simplified/releases/download/3.6.1%2B20251013122507/kanjidic2-en-3.6.1%2B20251013122507.json.tgz
          tar -xzf kanjidic2.json.tgz
          ls -la  # Debug: see what files were extracted
          # Find and rename the extracted file (handle any filename variations)
          find . -name "kanjidic2-en-3.6.1*.json" -exec mv {} kanjidic2-en-3.6.1.json \;
          rm kanjidic2.json.tgz

          # Download JMnedict (Japanese Names Dictionary)
          curl -L -o jmnedict-all.json.tgz \
            https://github.com/scriptin/jmdict-simplified/releases/download/3.6.1%2B20251013122507/jmnedict-all-3.6.1%2B20251013122507.json.tgz
          tar -xzf jmnedict-all.json.tgz
          ls -la  # Debug: see what files were extracted
          # Find and rename the extracted file (handle any filename variations)
          find . -name "jmnedict-all-3.6.1*.json" -exec mv {} jmnedict-all-3.6.1.json \;
          rm jmnedict-all.json.tgz
      
      - name: Build Rust project
        run: cargo build --release
      
      - name: Build dictionary shard
        run: |
          cargo run --release --bin merge_dictionaries -- \
            --individual-files \
            --mode ${{ matrix.shard }}
      
      - name: Count files in shard
        id: count
        run: |
          # When using --mode, files are output to output_dictionary/
          SHARD_DIR="output_dictionary"
          if [ -d "$SHARD_DIR" ]; then
            FILE_COUNT=$(find "$SHARD_DIR" -name "*.deflate" | wc -l)
            echo "file_count=$FILE_COUNT" >> $GITHUB_OUTPUT
            echo "✓ Shard ${{ matrix.shard }}: $FILE_COUNT files"
          else
            echo "❌ Shard directory $SHARD_DIR not found!"
            echo "Available directories:"
            ls -la | grep "output"
            exit 1
          fi
      
      - name: Verify file count is reasonable
        run: |
          FILE_COUNT=${{ steps.count.outputs.file_count }}
          SHARD="${{ matrix.shard }}"

          # Allow reserved shard to be empty (it's for future growth)
          if [ "$SHARD" = "reserved" ]; then
            echo "✓ Reserved shard can be empty (has $FILE_COUNT files)"
          elif [ "$FILE_COUNT" -lt 1000 ]; then
            echo "❌ Error: Only $FILE_COUNT files generated (expected at least 1,000)"
            exit 1
          elif [ "$FILE_COUNT" -gt 500000 ]; then
            echo "❌ Error: $FILE_COUNT files generated (expected max 500,000)"
            exit 1
          else
            echo "✓ File count looks good: $FILE_COUNT files (10-shard system)"
          fi
      
      - name: Clone target repository
        run: |
          git clone "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Kimeiga/kiokun2-dict-${{ matrix.shard }}.git" target-repo
      
      - name: Sync files to target repository
        run: |
          SHARD_DIR="output_dictionary"

          # Clear the target repository (keep only .git)
          find target-repo -mindepth 1 -name '.git' -prune -o -exec rm -rf {} +

          # Copy files using rsync to avoid "Argument list too long" error
          # This handles large numbers of files (400K+) that cp can't handle
          rsync -a "$SHARD_DIR/" target-repo/

          echo "✓ Synced files to target repository"
      
      - name: Commit and push to target repository
        run: |
          cd target-repo
          
          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Create orphan branch (no history to keep repo small)
          git checkout --orphan temp-branch
          
          # Add all files
          git add -A
          
          # Commit
          git commit -m "Update dictionary shard ${{ matrix.shard }} - $(date -u +%Y-%m-%d)"
          
          # Force push to main (replaces all history)
          git branch -D main || true
          git branch -m main
          git push -f origin main
          
          echo "✓ Pushed to kiokun2-dict-${{ matrix.shard }}"

